# -*- coding: utf-8 -*-
"""Continuando com Collections.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12l1TMqh-KRqcsIEYSaC4S7rKYOemUkrc

# Aula 01
"""

usuarios_data_science = [15, 23, 43, 56]
usuarios_machine_learning = [13, 23, 56, 42]

assistiram = usuarios_data_science.copy()
assistiram.extend(usuarios_machine_learning)
assistiram

len(assistiram)

set(assistiram)

set([1, 2, 3, 1])

{1, 2, 3, 1}

type({1, 1, 2})

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

for usuario in assistiram:
  print(usuario)

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

usuarios_data_science | usuarios_machine_learning # união de dois conjuntos

usuarios_data_science & usuarios_machine_learning # elementos que aparecem nos dois conjuntos

usuarios_data_science - usuarios_machine_learning

fez_ds_mas_nao_fez_ml = usuarios_data_science - usuarios_machine_learning
15 in fez_ds_mas_nao_fez_ml

23 in fez_ds_mas_nao_fez_ml

usuarios_data_science ^ usuarios_machine_learning # or exclusivo

"""# Aula 02"""

usuarios = {1, 5, 76, 34, 52, 13, 17}
len(usuarios)

usuarios.add(13)
usuarios

usuarios.add(765)
usuarios

usuarios = frozenset(usuarios) # congela o conjunto, ou seja, não permite alterar o conjunto
type(usuarios)

meu_texto = "Bem vindo, meu nome é thiago, eu gosto muito de cachorro e também gosto muito de estudar"

palavras = meu_texto.split(" ")
set(palavras)

"""# Aula 03"""



"""# Aula 04"""



"""# Aula 05"""

